FROM python:3.12

RUN mkdir /usr/src/app

COPY main.py /usr/src/app

COPY requirements.txt /usr/src/app

WORKDIR /usr/src/app

RUN pip install -r requirements.txt

EXPOSE 8081

CMD ["fastapi", "run", "main.py", "--port=8081"]
