version: '3.8'

services:

  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/PGDATA
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=smarthome
      - PGDATA=/var/lib/postgresql/data/PGDATA    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smarthome"]
      interval: 10s
      timeout: 5s
      retries: 5
    tty: true
    stdin_open: true
    networks:
      - smarthome-network


  temperature-api:
    build:
      context: ./temperature-api
      dockerfile: Dockerfile
    container_name: temperature-api-app
    ports:
      - "8081:8081"
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      smarthome-network:
        aliases:
          - temperature-api

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
    ports:
      - "8080:8080"
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - smarthome-network
    
volumes:
  postgres_data:
    driver: local

networks:
  smarthome-network:
    internal: true
    driver: bridge