@startuml
!include <C4/C4_Container>

System_Boundary(system1, "Микросервис просмотра телеметрии") {
    Container(frontend, "Микрофронтенд взаимодействия с пользователями", "Экранные формы для телеметрии")
    Container(backend, "Серверная часть микросервиса просмотра телеметрии", "Реализация бизнес-логики телеметрии")
    ContainerQueue(sensor_queue, "Очередь сообщений для получения телеметрии с датчиков")
    ContainerDb(db_conf, "База данных настроек микросервиса", "Конфигурационные данные для получения телеметрии с датчиков")
    ContainerDb(db_data, "База данных для хранения данных телеметрии")
}

Person(personAlias, "Пользователи")

Rel(frontend, personAlias, "Получение данных телеметрии")
Rel(backend, frontend, "Получение данных телеметрии")
Rel(sensor_queue, backend, "Получение данных с датчиков")
Rel(backend, db_conf, "Хранение настроек микросервиса")
Rel(backend, db_data, "Хранение данных микросервиса")

Container(sensors, "Датчики")
Rel(sensors, sensor_queue, "Получение данных с датчиков", "Асинхронное взаимодействие")


@enduml