@startuml 

interface Интерфейс_датчика {
    инициализация()
    старт()
    стоп()
    чтение()
    запись()
}

class Датчик_отопления {
    инициализация()
    старт()
    стоп()
    чтение()
    запись()
    включить_отопление()
    выключить_отопление()
}


 Интерфейс_датчика <|- Датчик_отопления


@enduml